// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Svendeprøve.Repo.DatabaseContext;

#nullable disable

namespace Svendeprøve.Repo.Migrations
{
    [DbContext(typeof(Databasecontext))]
    partial class DatabasecontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Svendeprøve.Repo.DTO.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            id = 28,
                            name = "Action"
                        },
                        new
                        {
                            id = 12,
                            name = "Adventure"
                        },
                        new
                        {
                            id = 16,
                            name = "Animation"
                        },
                        new
                        {
                            id = 35,
                            name = "Comedy"
                        },
                        new
                        {
                            id = 80,
                            name = "Crime"
                        },
                        new
                        {
                            id = 99,
                            name = "Documentary"
                        },
                        new
                        {
                            id = 18,
                            name = "Drama"
                        },
                        new
                        {
                            id = 10751,
                            name = "Family"
                        },
                        new
                        {
                            id = 14,
                            name = "Fantasy"
                        },
                        new
                        {
                            id = 36,
                            name = "History"
                        },
                        new
                        {
                            id = 27,
                            name = "Horror"
                        },
                        new
                        {
                            id = 10402,
                            name = "Music"
                        },
                        new
                        {
                            id = 9648,
                            name = "Mystery"
                        },
                        new
                        {
                            id = 10749,
                            name = "Romance"
                        },
                        new
                        {
                            id = 878,
                            name = "Science Fiction"
                        },
                        new
                        {
                            id = 10770,
                            name = "TV Movie"
                        },
                        new
                        {
                            id = 53,
                            name = "Thriller"
                        },
                        new
                        {
                            id = 10752,
                            name = "War"
                        },
                        new
                        {
                            id = 37,
                            name = "Western"
                        });
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hall");
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.Seat", b =>
                {
                    b.HasOne("Svendeprøve.Repo.DTO.Hall", null)
                        .WithMany("Seats")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.Ticket", b =>
                {
                    b.HasOne("Svendeprøve.Repo.DTO.User", null)
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.Hall", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Svendeprøve.Repo.DTO.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
